import { Footer } from "@/components/footer/footer";
import "../globals.css";
import Header from "@/components/header/header";




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className="flex flex-col min-h-screen">
        <Header />
        <div className="flex-grow my-16 min-h-full md:min-h-auto">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
