import { AdminSlideBar } from '@/components/admincomponents/adminSlidebar/slidebar'
import React from 'react'
import '../../globals.css'
import './style.css'


export const metadata = {
    title: "Admin panel",
    description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
    return (
        <html>
            <body dir='rtl' lang='fa'>
                <div className='m-0 flex '>
                    <AdminSlideBar />
                    <div className='flex-[3]'>{children}</div>
                </div>
            </body>
        </html>
    )
}

